name: commit-buddy
description: AI-powered commit message generator
command: C:\Users\Gotri\AppData\Local\Programs\Python\Python313\python.exe
args:
- .kiro/scripts/commit_buddy.py
- --from-diff
triggers:
- manual
workingDirectory: .
env:
  PYTHONPATH: .kiro/scripts
